### ISSUE TITLE
as long as "Generate Collision for Mesh Data" is opened, the button can't be clicked in ue4.26.1

### ISSUE THREAD

**Issue by YiRonger** [microsoft/MixedReality-UXTools-Unreal#26] opened 2021-02-25 00:14 UTC
Hello, 
Using version 0.11
UE Version 4.26.1
 As long as "Generate Collision for Mesh Data" is opened in ARSession, the button can't be clicked in ue4.26.1.

In ue4.25, I can click normally even if I select  "Generate Collision for Mesh Data", but not in ue4.26.

**Comment by EVRTOP** [comment] 2021-03-04 08:52
@macborow Hello, do you have any updates?

**Comment by macborow** [comment] 2021-03-04 11:54
Sorry about the delay. I haven't had a chance to check this yet but I'll look into it shortly.

**Comment by macborow** [comment] 2021-03-04 18:02
The issue is caused by the collisions with reconstructed hand mesh and is a know issue at the moment. We are working on a fix but it will require changes in the Unreal Engine, so it will not be available right away. For now please use the following workaround which disables collisions for the hand mesh.

Assuming Start AR Session is called in Begin Play (inside Game Mode), you can use the following steps:
- Open Game Mode Blueprint for editing
- Add a new function called ToggleHandCollisions with an input named Geometry (type ARTracked Geometry object reference). The image blow shows how to disable collisions for the Hand Mesh only (the check uses GetObjectClassification and ==(Enum) to identify the Hand Mesh):
![image](https://user-images.githubusercontent.com/4139054/110006287-5cd04080-7d11-11eb-92d6-b789a437e883.png)
- Add ARTrackableNotify component (default component) to Game Mode
- Add ARTrackableNotify OnAddTrackedGeometry and OnUpdateTrackedGeometry events and make them call the ToggleHandCollisions function:
![image](https://user-images.githubusercontent.com/4139054/110006456-9903a100-7d11-11eb-982e-f8348f024f20.png)

There was also a great walk through of this workaround in the recent UE4 webinar - https://youtu.be/t95Bge-yk5E at ~50:45 (information about enabling collision data in AR Session starts at ~49:00). The video also explains how to deal with a slightly more complex use case involving caching spatial meshes in an array and enabling/disabling them on demand with a button.

**Comment by YiRonger** [comment] 2021-03-05 01:48
OK, I see. Thank you very much!

**Comment by macborow** [comment] 2021-06-28 15:43
Just a quick update on this issue - we added a workaround for this problem in UXTools 0.12.x release. Hand collisions are now automatically updated by UXTools and the changes in Blueprint which I mentioned earlier are no longer necessary.
The root cause has been fixed in Unreal Engine 4.27 and I have just checked that the fix is included in 4.27.0-preview2 build.

**Closed by macborow** 2021-06-28 15:43 UTC

**Comment by YiRonger** [comment] 2021-08-12 08:15
> Just a quick update on this issue - we added a workaround for this problem in UXTools 0.12.x release. Hand collisions are now automatically updated by UXTools and the changes in Blueprint which I mentioned earlier are no longer necessary.
> The root cause has been fixed in Unreal Engine 4.27 and I have just checked that the fix is included in 4.27.0-preview2 build.

OK, I see. Thank you so much!
