### ISSUE TITLE
Is the hand model provided for simulation only?

### ISSUE THREAD

**Issue by JimSimons-UH** [microsoft/MixedReality-UXTools-Unreal#48] opened 2021-11-08 14:15 UTC
Hi, 

It looks like the provided hand animblueprint is for simulation only, such that when using real world hand tracking data, there isn't a rigged hand provided. Is this the intention (because of AR) or is there a way of adding a rigged hand to the scene within the toolkit?

**Comment by luis-valverde-ms** [comment] 2021-11-08 14:50
Hi @JimSimons-UH . That is by design indeed: the blue hands are there to stand for the real hands that you would see when actually running in AR. See [here ](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unreal/unreal-hand-tracking?tabs=426#hand-mesh-visualization-in-openxr) for documentation on how to add mesh visualization for hands. I'm closing this issue for now but feel free to reopen it if you want to discuss it further.

**Closed as completed by luis-valverde-ms** 2021-11-08 14:50 UTC
